FROM node:14-slim

WORKDIR /usr/src/app


COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy local code to the container image.
COPY . .

# Expose the port the app runs in
EXPOSE 8080

# Run the web service on container startup.
CMD [ "npm", "start" ]